### ISSUE TITLE
Damage Calculator related

### ISSUE THREAD

**Issue by DizzyEggg** [EternalCode/Battle-System#12]
1. Add Body Slam, Dragon Rush, Flying Press, and Phantom Force to 
double damage when used against a minimized foe. 2053
2. Whirlpool does double damage if used against a foe that used Dive
3. Magnitude does double damage against a foe that used Dig.
4. 1775 Seismic Toss also does attacker's lvl in dmg.
5. 1346 Add Huge Power to Pure Power.
6. 1450 It seems special attack affects Defense, not Special Defense.
7. 1189 Rivalry also lowers damage when fighting a foe that is of opposite gender(0.75 %). 
8. 1999 Tinted Lens. 

if...(flags->effectiveness)) {...

effectiveness should have a value.
9. 770 Stored Power doesn't take into account crit multipliers. 
10. 901 Thunder also deals double damage to a target that used Fly, Bounce or Sky Drop.

**Comment by EternalCode** [comment]
Thanks. I've fixed these now!

**Comment by DizzyEggg** [comment]
You omitted the Tinted Lens one.
